### PR TITLE
hashlib: import pure python hash first to unbreak the hmac module

### PR DESCRIPTION
**Pull request by mvo5**
With the current import strategy that favours the uhashlib
implementation before using the "internal" hashlib version external
modules like "hmac" break because the uhashlib versions lack properties
like `{digest,block}_size, copy()`.

This commit changes the import so that the internal version of the
hash is tried to be imported first and only if there is no internal
version then the uhashlib version is used.

This should fix https://github.com/micropython/micropython-lib/issues/384

I guess as an alternative we could try to make uhashlib compatible with hmac.
This should be relatively straightforward and was done in https://github.com/micropython/micropython/pull/4539 but wasn't received favorable there.

### CODE REVIEW

**Comment by mvo5** [comment]
I love micropython and would love to see this issue fixed. Is there anything I can do/should do to move this forward? I'm happy to write test cases or anything else that might help :)

**Comment by tfindlay-au** [comment]
@jimmo Can you provide some feedback on this PR ?
I know a few people that are held up by the issue that this would resolve if its accepted.

**Comment by jimmo** [comment]
Thanks @mvo5 and sorry this has taken so long.

It's preferable to use the built-in one where possible -- e.g. an app that only needs to do sha256 hmacs shouldn't need to install hashlib from micropython-lib if the device already has it.

I agree it would be good to update uhashlib's ones to support hmac (as per https://github.com/micropython/micropython/pull/4539) but hmac strictly doesn't need these extensions to function. So instead I think it's better to solve this by making the `hmac` module able to use the built-in ones as they are. See #515

**Comment by mvo5** [comment]
Thanks @jimmo - using the buildin hashes by default of course makes a ton of sense - thank so much for fixing hmac with the buildin hashes too, really appreicated!

**Pull request closed without merging**
