### PR TITLE
Update ntptime.py

### PR DESCRIPTION
**Pull request by yanzhonghui**
Add time zone offset support

### CODE REVIEW

**Comment by projectgus** [comment]
Thanks @MrEbbinghaus for gathering all these PRs together. I generally agree with your conclusion and suggested approach.

Many (but I think not all) ports are built with `MICROPY_PY_TIME_GMTIME_LOCALTIME_MKTIME` support which implements 90% of what's needed for CPython compatible timezone support inside `extmod/modtime.c`. At first glance, the only thing that's missing to implement for basic embedded-friendly time zones is [time.timezone](https://docs.python.org/3.5/library/time.html#time.timezone), and the fact that `gmtime()` and `localtime()` are implemented as the same function.

I feel like there's probably a good reason why this isn't implemented already, though. @dpgeorge and @jimmo might know?

**Comment by projectgus** [comment]
Oh, I see it. [`struct time` in Micropython](https://docs.micropython.org/en/latest/library/time.html#time.localtime) only has the first 8 fields of the [equivalent in CPython](https://docs.python.org/3.5/library/time.html#time.struct_time). So there's no way to add timezones here and keep backwards compatibility.

**Comment by MrEbbinghaus** [comment]
A complete time zone database support would be unnecessary.

One could implement something like `time.tzset()`
For my current timezone this would be: 
`CET-1` (without DST)
`CET-1CEST,M3.5.6,M10.5.6/3` (with DST)

From that we could set 
`time.``daylight`

**Comment by projectgus** [comment]
@MrEbbinghaus Good ideas, both on moving this discussion to a more suitable place, and the possibility of simplified timezone string support.

I've summarised all of the existing discussion and options I could find, here: https://github.com/orgs/micropython/discussions/12378 - please reply with more thoughts or suggestions.

@yanzhonghui As discussed above, everyone agrees MicroPython should solve this problem but the best place is probably not in the `ntptime` module. As such, I'm going to close this PR. Please comment on the linked discussion if you have any suggestions for what should be done!

**Pull request closed without merging**
