### PR TITLE
contextlib: port ExitStack from CPython 3.4

### PR DESCRIPTION
**Pull request by dxxb**
See discussion in #49

### CODE REVIEW

**Comment by dxxb** [comment]
I am not sure I like the fact I changed instances of of assertIsNone() to _assert is None_. I'm happy to add assertIsNone() to unittest and get back to this.

**Comment by pfalcon** [comment]
> I am not sure I like the fact I changed instances of of assertIsNone() to assert is None. I'm happy to add assertIsNone() to unittest and get back to this.

Sure, feel free to, unittest is not size-critical (it's just big mess o'code from my point of view, so I didn't even try to port it, instead was adding method on as-needed basis, other contributed a bunch too).

**Comment by dxxb** [comment]
I'd rather use 'assert x is None' directly but it would result in more line changes when porting tests from CPython. I have created #52 and rebased this PR on it.

**Comment by dxxb** [comment]
Hi @pfalcon, this is ready to be reviewed.

**Comment by dxxb** [comment]
PR updated. Prefixed incompatible test names with underscore.

**Comment by pfalcon** [comment]
Merged, thanks.

**Comment by dxxb** [comment]
Apologies for the oversight and thank you.

**Pull request merged**
