### PR TITLE
Dxxb/ucontextlib

### PR DESCRIPTION
**Pull request by dxxb**
Minimal module spin off from existing contextlib as discussed in Issue #49.
Test were broken because of changes to unittest.run_class() so I moved to invoking unittest.main().
Not sure what to change the description in metadata and doctext to.

### CODE REVIEW

**Comment by pfalcon** [comment]
I'll merge this as is, but preference should be on making as little as possible changes to CPython tests (by byte size of the resulting diff). By this logic, ContextManagerTestCase should not have been removed (regardless whether it's duplicated in ucontextlib module).

**Comment by pfalcon** [comment]
You also apparently don't use make_metadata.py utility, but edit setup.py manually, which leads to mistakes. Please follow https://github.com/micropython/micropython-lib/wiki/ContributorGuidelines

**Comment by dxxb** [comment]
Hi, I thought duplicating the test case would lead to PR rejection. I can fix that and use make_metadata.py to generate setup.py

**Comment by pfalcon** [comment]
Merged with number of metadata changes.

**Comment by dxxb** [comment]
Thanks

**Comment by pfalcon** [comment]
> Hi, I thought duplicating the test case would lead to PR rejection.

This matter also covered in https://github.com/micropython/micropython-lib/wiki/ContributorGuidelines . And those guidelines are not arbitrary, but rooted in the fact that maintaining a project with dozen of individual components isn't easy, moreover if majority of components come from other projects.

> I can fix that and use make_metadata.py to generate setup.py

Well, I don't want to block on this, but please follow those guidelines in the future ;-)

**Comment by dxxb** [comment]
Thank you. Point taken! :)

**Pull request closed without merging**
