### PR TITLE
Pass return values from partial wrappers

### PR DESCRIPTION
**Pull request by betabrain**
Obvious.

### CODE REVIEW

**Comment by pfalcon** [comment]
As obvious as the need to follow https://github.com/micropython/micropython-lib/wiki/ContributorGuidelines ;-).

**Comment by betabrain** [comment]
Updated (forced push to keep things clean - not sure if that generates a notification). Hope you are happy. ;-)

**Comment by betabrain** [comment]
**Aside:**
- What's he idea behind the naming distinction: **uname** vs **name**?
- Are there any plans to track and store compatibility with the non-unix platforms, e.g. in `metadata.txt`?

**Comment by pfalcon** [comment]
> Updated (forced push to keep things clean - not sure if that generates a notification).

It doesn't. And indeed, pushes aren't replacement for human communication ;-). Thanks.

**Comment by pfalcon** [comment]
> What's he idea behind the naming distinction: uname vs name?

Did you try to read docs? (Granted, that passage isn't even shown in "unix" port docs): http://docs.micropython.org/en/latest/pyboard/library/index.html#micropython-libraries

That should get you started, feel free to ask further specific questions.
 
> Are there any plans to track and store compatibility with the non-unix platforms, e.g. in metadata.txt?

No, there's no manpower for that. Paving the ground for that is welcome though. You may want to review http://forum.micropython.org/viewtopic.php?f=16&t=2544#p14957 (but I personally don't think that what deshipu proposes is right way to do it).

**Comment by pfalcon** [comment]
Merged/published to PyPI, thanks.

**Pull request merged**
