### PR TITLE
uasyncio.core: Fix scheduling in the presense of I/O completion callbacks.

### PR DESCRIPTION
**Pull request by pfalcon**
wait() may finish prematurely due to I/O completion, and schedule new,
earlier than before tasks to run. So, after call to wait(), we need to
check current time and time of head task, and continue to wait if needed.
Recently introduced provisional utimeq.peektime() is used to optimize
querying time of a head task.

### CODE REVIEW

**Comment by pfalcon** [comment]
For review to: @dpgeorge , @peterhinch, @prusnak, @jpochyla.

Note that there's a testcase which now passes: https://github.com/micropython/micropython-lib/commit/aa9bbe839eac5bce0a0e5169f63730b13a638b64 . Full uasyncio integration tests weren't yet run though.

**Comment by dpgeorge** [comment]
It looks ok to me.

**Comment by peterhinch** [comment]
It fixes https://github.com/micropython/micropython/issues/3005.

**Comment by pfalcon** [comment]
Ok, thanks for testing! I also ran standard uasyncio integration tests, all's ok, so I'm merging this to master. But not tagging a new release yet, so there's still time to catch last-minute regressions ;-).

**Comment by pfalcon** [comment]
Finally pushed to PyPI.

**Pull request closed without merging**
