### PR TITLE
micropython/aiorepl: Add paste mode and raw repl.

### PR DESCRIPTION
**Pull request by Carglglz**
This adds a paste mode to  `aiorepl` and a "raw REPL" mode to enable compatibility with MicroPython development tools .e.g `pyboard.py`/`mpremote` and other tools that use the raw REPL mode to communicate with the device.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Sorry I didn't see this!  It got superseded by #756.

**Comment by Carglglz** [comment]
Don't worry #756 had more features than this one, also I think that it's worth exploring the idea of developing an
 `_aiorepl`  C module to get it working as close as normal REPL/raw REPL (e.g.  autocompletion, `;` chained commands, etc)

**Comment by andrewleech** [comment]
I also just apologize, I didn't know of this work you'd done before I started mine, if nothing else I'd prefer to have built in top of yours rather than writing from scratch!

While working on this space I did look at just exposing the C code rather than re-writing in python, but the structure of how repl works was making this surprisingly difficult!

Maybe it is still worth breaking out smaller chunks to use, but that does at the flash overhead of said python interface code that everyone gets regardless of whether they use aiorepl.
I'd be keen to figure out a way to make the built in repl able to be re-run in async. 

This modded micropython apparently has some async support in the repl, but it's all mashed into the one mega-commit, I haven't looked into exactly what's been done with the repl:
https://github.com/gneverov/micropythonrt

**Comment by andrewleech** [comment]
I also just apologize, I didn't know of this work you'd done before I started mine, if nothing else I'd prefer to have built in top of yours rather than writing from scratch!

While working on this space I did look at just exposing the C code rather than re-writing in python, but the structure of how repl works was making this surprisingly difficult!

Maybe it is still worth breaking out smaller chunks to use, but that does at the flash overhead of said python interface code that everyone gets regardless of whether they use aiorepl.
I'd be keen to figure out a way to make the built in repl able to be re-run in async. 

This modded micropython apparently has some async support in the repl, but it's all mashed into the one mega-commit, I haven't looked into exactly what's been done with the repl:
https://github.com/gneverov/micropythonrt

**Pull request closed without merging**
