### PR TITLE
uuid: provide basic random uuid4() implementation

### PR DESCRIPTION
**Pull request by andrewleech**
This provides a random uuid4() function which returns a string, rather than a UUID class like the python builtin.

### CODE REVIEW

**Comment by dhylands** [comment]
I did something similar a while ago: https://github.com/micropython/micropython-lib/pull/282 but I think that the PR needs to go against pfalcon's repository:
https://github.com/pfalcon/micropython-lib

**Comment by andrewleech** [comment]
Ah whoops, I was sure I did a search beforehand.... clearly not.

Yours looks much better in general, however I followed https://www.cryptosys.net/pki/uuid-rfc4122.html in setting a couple of magic bits for uuid4, did not bother to cross-reference it for correctness though.

**Comment by andrewleech** [comment]
If PR's do need to be made against @pfalcon 's repo, it would be worth adding that to the https://github.com/micropython/micropython-lib/wiki/ContributorGuidelines

**Comment by pfalcon** [comment]
Well, it's said here: https://forum.micropython.org/viewtopic.php?f=15&t=70 , and https://github.com/pfalcon/micropython-lib/wiki/ContributorGuidelines doesn't contradict.

**Comment by andrewleech** [comment]
Sorry if my comment sounded a bit abrupt or harsh, it definitely wasn't intended as such. I'm very comfortable changing my remote / PR target to best suit your workflow!

When I opened the pull request it gave a popup to read through the guidelines I linked to (which are nearly identical to the one on your repo) so a note there requesting PR's target your repo could help avoid confusion.

Speaking of which though, do you prefer PR's be opened on your repo rather than here? 
Sorry if I'm missing something but I can't see any reference to this on the forum page or your contributor guidelines.

**Comment by pfalcon** [comment]
> Speaking of which though, do you prefer PR's be opened on your repo rather than here?

I, the author and maintainer of the micropython-lib project, welcome interested parties who have been using this project, or new users, and who are interested to contribute to it (or just use), to do so at the master location, https://github.com/pfalcon/micropython-lib . A fork here was a failed experiment (failed not by me).

https://forum.micropython.org/viewtopic.php?f=15&t=70 links to https://github.com/pfalcon/micropython-lib in first, last (as typically read) and intermediate messages. I'm not sure how to make my invitation clearer. The project here belongs to a particular party (who happen to be the direct cause of the situation) and I don't feel like meddling with their fork by editing wikis redirecting away. (However, if a particular user asks what's the best way to get a patch processed, I'm happy to provide the response above.)

**Comment by andrewleech** [comment]
Thank you for your clear response, it's much appreciated and makes much more sense to me now.

**Pull request closed without merging**
