### PR TITLE
micropython: Migrate drivers/libraries from main repo to micropython-lib.

### PR DESCRIPTION
**Pull request by jimmo**
This adds all Python code from drivers/ and extmod/ in the main repo.

The idea is to make these libraries all available via `require("foo")` in a manifest, and also (soon) installable via upip/mpremote/etc.

### CODE REVIEW

**Comment by jimmo** [comment]
Note: asyncio is left out of this PR because I want to move the docs over too, and first we need to set up how documentation from micropython-lib will be integrated into the main docs build.

**Comment by dpgeorge** [comment]
We need to think of a standard for commit messages.  Eg if making changes to `lps22h` does the commit message start with `micropython:`, `micropython/drivers:`, `micropython/drivers/sensor/lps22h:` or `lps22h:`, or something else?

**Comment by jimmo** [comment]
> We need to think of a standard for commit messages. Eg if making changes to `lps22h` does the commit message start with `micropython:`, `micropython/drivers:`, `micropython/drivers/sensor/lps22h:` or `lps22h:`, or something else?

`lps22h:`

Rationale: All the leaf directory names are unique.

(Except for unix-ffi, but then it can be e.g. `unix-ffi/re`)

**Comment by dpgeorge** [comment]
Sounds good!

**Pull request merged**
