### PR TITLE
upip: Initialize socket with protocol family as gotten from resolver.…

### PR DESCRIPTION
**Pull request by michaelschrijver**
Fixes issue #2296 (tracked in micropython repo).

### CODE REVIEW

**Comment by dpgeorge** [comment]
That's an easy fix!  Were you able to test that it worked with IPv6 addresses?

**Comment by michaelschrijver** [comment]
Yep it's working for me. I've only tested the unix port though.

**Comment by dpgeorge** [comment]
Other ports should return the correct structure fromthe  getaddrinfo call, so they should also work.

**Comment by pfalcon** [comment]
Merged, thanks. I'll push new version of upip a bit later.

**Pull request closed without merging**
