### PR TITLE
drivers/sensor/dht: Change the sequence for importing dht_readinto.

### PR DESCRIPTION
**Pull request by robert-hh**
Check the machine module first, then try the port specific places.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I'm not sure what this achieves?  One thing it does do is make the code bigger with the additional error message :smile: 

Probably best to just move all `dht_readinto` methods on the ports into `machine`, and then make this module just do `from machine import dht_readinto` unconditionally.

**Comment by robert-hh** [comment]
The intention is legacy, such that the 'new' dht.py works with previous versions of the firmwarem, at least for a while.

**Comment by dpgeorge** [comment]
Oh, I see!  Yes that makes sense then.

Probably good to add a comment then, why the older imports are there.

Also, except for the esp case, the port-specific cases can actually be combined to:
```py
dht_readinto = __import__(sys.platform).dht_readinto
```

**Comment by dpgeorge** [comment]
Squashed and merged in 0e25b109c23fe30a3a0f075c0edf2c2564bc5046

**Pull request closed without merging**
