### PR TITLE
 umqtt.simple: refactor packet de/encoding and fix remaining length encoding (fixes #284)

### LINKED ISSUE #284: umqtt subscribe to topic with 23 bytes fails
Hi, 
I can't subscribe to topic longer than 122 bytes. Publishing works fine!
I kindly ask you to verify and hopefully fix it
Thanks a lot
Danny

OK - working:
```
#122 bytes
mqtt.subscribe(b"/234567890/234567890/234567890/234567890/234567890/234567890/234567890/234567890/234567890/234567890/234567890/234567890/2") 
```
but one more character:
```
#123 bytes
mqtt.subscribe(b"/234567890/234567890/234567890/234567890/234567890/234567890/234567890/234567890/234567890/234567890/234567890/234567890/23") 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test.py", line 169, in <module>
  File "umqtt_simple.py", line 154, in subscribe
  File "umqtt_simple.py", line 173, in wait_msg
OSError: -1
```

this might be related to #163 which also deals with 127 bytes

it might be related to https://github.com/micropython/micropython-lib/blob/f20d89c6aad9443a696561ca2a01f7ef0c8fb302/umqtt.simple/umqtt/simple.py#L148 as this is hitting the 128...

### PR DESCRIPTION
**Pull request by SpotlightKid**
As stated in #284, the `MQTTClient.subscribe` method doesn't handle topic lengths >= 122 correctly, since it only allocates one byte for the remaining length portion of the SUBSCRIPTION packet. I've refactored the variable length encoding of the remaining length bytes to use the new `_varlen_encode` method consistently and also got rid of the usage of the `ustruct` module.

* Add `_varlen_encode` method to write variable length encoded remaining length bytes to packet buffer and use it consistently.
* Use `int.from_bytes/to_bytes` to de/encode short integers and replace `ustruct` usage with it.
* Correctly separate bytes of fixed and variable header in `connect` method.

In a separate commit I've also removed all (commented ou) debug printing calls in `simple.py` and added a debug wrapper for `MQTTClient` (`umqtt_debug.py`) to the examples, which can optionally be used with examples, and I've also expanded `example_pub.py` and `example_sub.py` so that they can be parametrized form the command line. If desired, I can separate this commit into an extra PR.

This PR is based on the branch for PR #302. If the latter is merged, I will rebase this on master.

### CODE REVIEW

**Comment by Kriechi** [comment]
@pfalcon this looks like an important bugfix - any chance you could review this?

**Comment by SpotlightKid** [comment]
@Kriechi It seems that only the fork (or original, depending on how you look at it) of `micropython-lib`at https://github.com/pfalcon/micropython-lib is maintained and developed any further, ATM.

I could re-submit my PR there, but I have basically given up on MicroPython, and I probably won't put any more effort into it. Feel free to take this PR (and any others I have made in this repo) and re-submit to pfalcon's repo.

**Comment by dl2080** [comment]
Thank you @SpotlightKid! Without your refactor bug fix I wasn't able to subscribe to my AWS topic, although it was only 63 bytes in length. Now it is working!

**Comment by SpotlightKid** [comment]
Closing this since I'm cleaning my unmerged PRs and this hasn't been acted upon in years.

**Pull request closed without merging**
