### PR TITLE
Itertools cycle

### PR DESCRIPTION
**Pull request by stinos**
See #41

### CODE REVIEW

**Comment by pfalcon** [comment]
Well, neat. But extra recursion in yield from doesn't help memory usage again. So, better to rewrite to avoid it (feel free to leave that to me).

**Comment by stinos** [comment]
Ah ok, fixed

**Comment by pfalcon** [comment]
Thanks, pushed, with a bit more optimization: https://github.com/micropython/micropython-lib/commit/91563f06db292d322428e43ce0b8c43dd0676702 . Also, did similar change for islice() - to be able to write tests for all this. (But decided against optimizing sequence case for islice(), after all, there's normal slice() for them).

**Comment by stinos** [comment]
Yes looks good, thanks.

**Pull request merged**
