### PR TITLE
argparse: Initial minimal implementation of argparse.

### PR DESCRIPTION
**Pull request by dpgeorge**
CPython's argparse needs around 160k heap just for the module, and has
heaps of dependencies.  This minimal version can run in 16k heap and has
only sys and namedtuple dependencies (which are builtin to MicroPython).

### CODE REVIEW

**Comment by pfalcon** [comment]
Looks good, though ideally, there would be example_*.py file showing what it can do (and as a manual smoke test).

Note that we should make some policy how to go about extending such "minimal, but functional" implementations. E.g. I already have https://github.com/micropython/micropython-lib/tree/master/utarfile , changes like https://github.com/micropython/micropython-lib/commit/2c2f6104f48830c7284ac083ab7e4b81007f493d make me wonder if I should split older implementation as ulogging, etc.

**Comment by dpgeorge** [comment]
> ideally, there would be example_*.py file

test_argparse.py now added (also serves as an example).

> Note that we should make some policy how to go about extending such "minimal, but functional" implementations.

Yes, I flipped between calling this uargparse and argparse.  If the aim is to be able to run existing Python programs unchanged then we need to have something called argparse.  This could be an extension of uargparse (to start with just from uargparse import *).

The main thing that CPython's argparse has that this one doesn't is pretty printing of the usage, including line wrapping and locale behaviour.  They add lots of bloat.

**Comment by pfalcon** [comment]
>  This could be an extension of uargparse (to start with just from uargparse import *).

Yes. Other approach of course to just try to port CPython module. Anyway, those are thoughts for future.

Looks good, please merge!

**Comment by dpgeorge** [comment]
> Other approach of course to just try to port CPython module.

I did manage to get CPython's argparse.py to run in uPy with minimal changes, but it took 160k heap, and thought that a micro-version would be a useful thing to have.

**Comment by dpgeorge** [comment]
Merged in eba0c0ad8dd4eaf747da9d6de9ebe116a3e1d4fa.

**Pull request closed without merging**
