### PR TITLE
unittest: Exit with non zero code in case of failures.

### PR DESCRIPTION
**Pull request by belyalov**
Fixing #259 

Successful run:
```
$ ./test_server.py; echo "Exit code $?"
testRequestLargeBody (ServerFull) ... ok
....
testMimeTypes (Utils) ... ok
Ran 34 tests

OK
Exit code 0
```

Failures:
```
$ ./test_server.py; echo "Exit code $?"
testRequestLargeBody (ServerFull) ... ok
....
testSendFileManual (StaticContent) ... FAIL
....
testMimeTypes (Utils) ... ok
Ran 34 tests

FAILED (failures=1, errors=0)
Exit code 1
```

### CODE REVIEW

**Comment by pfalcon** [comment]
I've merged to https://github.com/pfalcon/micropython-lib / released on PyPI. Thanks.

**Comment by belyalov** [comment]
Thanks,

Could you please explain what's wrong with this repository? It is considering as obsolete? Which one should I prefer?

**Comment by pfalcon** [comment]
It's complicated: https://forum.micropython.org/viewtopic.php?f=15&t=4358

**Comment by belyalov** [comment]
Can we merge this PR to this repository as well?

**Comment by belyalov** [comment]
@dpgeorge could you please take care of this repository which is part of micropython?

**Pull request closed without merging**
