### PR TITLE
umqtt.simple: do dns lookup in connect() method

### PR DESCRIPTION
**Pull request by puuu**
This is a alternative pull request for #161 and #155.

Tested with the micropython unix port.

### CODE REVIEW

**Comment by pfalcon** [comment]
Sorry, please test with esp8266 too ;-). And please describe your test procedure here. Thanks.

**Comment by puuu** [comment]
OK, tested with ESP8266 daily build (esp8266-ota-20170613-v1.9.1-4-g6ed4581f):

```python
import network
from  umqtt.simple import MQTTClient
#from  umqtt.robust import MQTTClient

SERVER = "test.mosquitto.org"

wlan = network.WLAN(network.STA_IF)
wlan.disconnect()
while wlan.isconnected():
    pass
c = MQTTClient("umqtt_client", SERVER)
wlan.connect()
while not wlan.isconnected():
    pass
c.connect()
c.publish(b"foo_topic", b"hello")
c.disconnect()
```

Both, umqtt.simple and umqtt.robust work after applying this PR.

**Comment by pfalcon** [comment]
Thanks! I also meant more details about your test setup - which MQTT broker you use, etc. These details are useful for maintainers as much as for other users - we already saw that there're wild varying results for different people, so unless we become specific about such things, we'll never know what works, what doesn't.

I'll merge this when I get a chance.

**Comment by puuu** [comment]
In my setups I use mosquitto (1.4.7) on OpenWRT router and mosquitto (1.3.4) on a Debian/Jessie server.

For this test I used the public mosquitto test broker `SERVER = "test.mosquitto.org"`.

Sorry, no other broker tested.

**Comment by pfalcon** [comment]
Thanks for stepping in to fix this, and for the detailed testing! Merged.

**Pull request closed without merging**
