### PR TITLE
Draft implementation of xmltok module

### PR DESCRIPTION
**Pull request by pfalcon**
Per https://github.com/micropython/micropython-lib/issues/37 .

One thing to decide whether attribute lists should be explicitly terminated or not. As you can see, I initially wanted to have terminators, and tokens for them were added, but skipped implementing them. With terminators, parsing will be slightly easier, but of course there's more garbage to collect. The reason I didn't implement them is because I thought that for many useful algos (see e.g. gfind() helper), you'd need to consume "next" token anyway. Then token stream would be represented by pair of (head, tail), where head is a token (or maybe None) and tail is generator.

That's all speculative though - I played with parsing UPNP responses a bit, but switched away from it.

### CODE REVIEW

**Comment by pfalcon** [comment]
Ah, also - should be get string.isalnum() ? Helps with writing parsers.

**Comment by dpgeorge** [comment]
There is going to be a lot of garbage if you generate START_TAG_END etc for each tag.  A lot of the time there are no attributes so it's not needed.  Perhaps there could be 2 different start tags, one when there are no attrs, one when there is 1 or more attrs, and this one has an end token?  Eg:
```
START_TAG "TagNoAttr"
...
START_TAG_ATTR "TagWithAttr"
ATTR attr1
ATTR_VAL val1
START_TAG_ATTR_END
```

Also, how about combining ATTR and ATTR_VAL into one returned "token"?  Attr vals are always strings (right?).  You're already returning a tuple with namespace + id, so why not add attr val?

> Ah, also - should [we impl] string.isalnum() ?

Yeah, sounds fine.

**Comment by pfalcon** [comment]
> Perhaps there could be 2 different start tags, one when there are no attrs, one when there is 1 or more attrs, and this one has an end token? Eg:

Nope, don't like that idea. It should be resource-efficient, but not at the expense of API clarity and ease of use - why burden users with matching 2 token types instead of 1? ;-)

> Also, how about combining ATTR and ATTR_VAL into one returned "token"? Attr vals are always strings (right?). You're already returning a tuple with namespace + id, so why not add attr val?

Well, namespace support is the latest addition. Before I really was thinking such things as: attribute name can be collected when value arrives ;-). But yes, with namespace support probably makes sense to combine them - beyond values lifetime issues, there doesn't seem to be more memory usage with such arrangement.

**Comment by pfalcon** [comment]
Ok, update code based on the discussion above. I guess, it can go to master in such shape, further adjustments may be made based on usage experience.

**Comment by pfalcon** [comment]
Ok, so I'm merging this now, keeping in mind that behavior may be tweaked later.

**Pull request closed without merging**
