### PR TITLE
logging: log to sys.stderr instead of sys.stdout

### PR DESCRIPTION
**Pull request by dxxb**
I am not sure if this will fly and how it affects non-unix ports but if we have to pick logging to stdout or stderr I would pick stderr.

### CODE REVIEW

**Comment by pfalcon** [comment]
Well, one risk is indeed non-unix ports. But otherwise, we should do it like upstream ;-). Providing direct references to docs will improve turnaround time.

**Comment by dpgeorge** [comment]
sys.stderr is relatively common in ports, so ok to use it like this.

CPython has concept of "handlers" and it seems the default one does indeed go to stderr: 
https://docs.python.org/3.4/library/logging.html#logging.basicConfig
https://docs.python.org/3.4/library/logging.handlers.html#logging.StreamHandler

**Comment by dxxb** [comment]
CPython defaults to sys.stderr when no destination is selected. micropython-lib's logging module does not support selecting a configuration right now so I guess it makes sense to default to sys.stderr. See [direct reference to docs](https://docs.python.org/3/howto/logging.html#what-happens-if-no-configuration-is-provided) ;-)

**Comment by pfalcon** [comment]
Thanks for references, guys. Merged.

@dxxb : Good start with the patches, feel free to submit/raise for discussion any other points you see. Thanks.

**Pull request closed without merging**
