### PR TITLE
Install by python script

### PR DESCRIPTION
**Pull request by pramasoul**
Implement <code>make install</code> with a python script per #10. Tested on Ubuntu 14.04.2 LTS and OSX 10.9.5.

### CODE REVIEW

**Comment by pfalcon** [comment]
> in python3 for uniform cross-platform behavior

Unfortunately, using python3 isn't *that* cross-platform. For example, we recently had a case of OpenWRT build failure, because python3 isn't among default host tools there.

@roger- : What would you say? ^^^

**Comment by pfalcon** [comment]
Overall, the script looks over-engineered for me.

~~~~
from distutils.dir_util import mkpath, copy_tree
~~~~

brings in avoidable dependencies. General rule of thumb I tried to follow is to write self-hosted tools (i.e. Python scripts which can be run with uPy itself). That single line breaks it. argparse dependency is not so breaking, but still not unavoidably necessary.

On a quick look, the script itself is also longer than I'd otherwise imagine.

**Comment by pfalcon** [comment]
Summing up: thanks, but I don't intend to merge this immediately. I'd rather wait couple of weeks in case:

1. You might rework it based on comments above.
2. Someone else might provide alternative implementation along the lines above.

**Comment by roger-** [comment]
In this case, yes, Python 3 isn't available but maybe it'll be good to have this as an option.

**Comment by pfalcon** [comment]
@pramasoul : So, any responses to comments above?

**Comment by pramasoul** [comment]
- Verified that <code>install_modules.py</code> works in python2.7 as well as python3. It now uses the system default python.
- "Down-engineered" the coding style

What approach do you recommend for accomplishing the file tree copies, in place of <code>distutils.dir_util.copy_tree</code>?

**Comment by pfalcon** [comment]
> What approach do you recommend for accomplishing the file tree copies, in place of distutils.dir_util.copy_tree?

There's os.walk() and glob already available, and if you really feel like that, you can implement shutil.copytree().

Thanks!

**Comment by pfalcon** [comment]
Ping - this patch's branch now has unrelated changes and needs a rebase or something.

**Comment by pfalcon** [comment]
Ping again.

**Comment by pramasoul** [comment]
Roger that. In the queue.

**Comment by pfalcon** [comment]
Thanks.

**Comment by puhitaku** [comment]
This PR is inactive for more than 1 year, and I've found that a Makefile in `master` branch is inconvenient for my macOS ( #10 ) so I want this to be merged ASAP.

My idea is that you can do merge-with-squash even if this branch has unrelated changes.

`make install` still works with both Python 2 / 3 flawlessly. I'm really into it. Thanks.

**Comment by puhitaku** [comment]
Ping @pfalcon

**Comment by jimmo** [comment]
Closing due to inactivity and a significant restructure of the way package installation works in micropython-lib.

**Pull request closed without merging**
