### PR TITLE
Fix out of memory error in ESP 32

### PR DESCRIPTION
**Pull request by jaejeong1**
Delete the wrap_socket causing the problem

### CODE REVIEW

**Comment by andrewleech** [comment]
I would expect these lines are needed for https support though?

**Comment by sosi-deadeye** [comment]
This won't fix anything, introduces a bug and makes `https` for all unusable.

[Redirects are not supported yet](https://github.com/micropython/micropython-lib/blob/master/micropython/urllib.urequest/urllib/urequest.py#L62), so you can't be redirected accidentally to `https` if you're using `http`. If you're using `https` it will trigger the `OSError: [Errno 12] ENOMEM` exception on Boards with less memory.

**Comment by mattytrentini** [comment]
Redirects have been implemented in `[urequests](https://github.com/micropython/micropython-lib/tree/master/python-ecosys/urequests)` (as well as a whole host of other fixes) and we should probably update `urlib.urequest` to use the same code.

**Comment by jimmo** [comment]
@jaejeong1 thanks but this is not the right solution as the other comments have pointed out.

We are working to fix this issue in the ESP32 SSL implementation, see https://github.com/micropython/micropython/issues/8940 for the main issue tracking this.

**Pull request closed without merging**
