### PR TITLE
gettext: implement gettext and ngettext

### PR DESCRIPTION
**Pull request by xrmx**
By wrapping the C counterparts

### CODE REVIEW

**Comment by pfalcon** [comment]
What's the motivation here?

**Comment by xrmx** [comment]
Being able to run software that use gettext :)

**Comment by pfalcon** [comment]
But not on a baremetal target which doesn't have libc and gettext? I'd like to be sure that contributors understand this, and that another contributor may propose to switch this implementation to a different one. With that in mind, it's ok.

**Comment by xrmx** [comment]
Sure, on the unix port of course, not on micro controllers.

**Comment by pfalcon** [comment]
Merged, thanks!

**Pull request closed without merging**
