### PR TITLE
Pystone lowmem

### PR DESCRIPTION
**Pull request by pfalcon**

### CODE REVIEW

**Comment by pfalcon** [comment]
@dpgeorge : Please check for soundness.

**Comment by dpgeorge** [comment]
Yes, it looks good!  pyboard gives exact same pystone value for original script and this lowmem version.

One thing: it would be more accurate (and one could run the test with a smaller number of iterations) to use a timing function that wasn't just seconds as integers.  For pyboard I have a modified pystone.py that uses pyb.millis() [which should be changed to time.ticks_ms() and time.ticks_diff()].

**Comment by pfalcon** [comment]
> pyboard gives exact same pystone value for original script and this lowmem version.

Well, on unix, lowmem is consistently and visibly slower (something like 50K vs 60K).

> should be changed to time.ticks_ms() and time.ticks_diff()

Ok, making this change.

**Comment by pfalcon** [comment]
Merged.

**Pull request closed without merging**
