### PR TITLE
micropython/bluetooth/aioble: save subscribed connections

### PR DESCRIPTION
**Pull request by MarceauFillon**
This change handles a new micropython event.
This event is fired upon susbcription update.
A characteristic now saves a list of subscribed connections.
This change depends on this PR: https://github.com/micropython/micropython/pull/7555

### CODE REVIEW

**Comment by jimmo** [comment]
Thanks for the PR!

I was hoping to make management (and awareness) of subscribed peers not something the application had to worry about, so hoping to find a way to achieve the same functionality without needing this. See https://github.com/micropython/micropython/pull/7555#issuecomment-884719968

**Comment by jimmo** [comment]
See https://github.com/micropython/micropython-lib/pull/437

**Comment by jimmo** [comment]
See https://github.com/micropython/micropython/pull/7564

**Comment by MarceauFillon** [comment]
Closing this issue as #437 has been implemented with a simpler and more elegant solution to this issue.

**Pull request closed without merging**
