### PR TITLE
binascii.unhexlify, base64, hashlib.sha224/256/384/512 

### PR DESCRIPTION
**Pull request by slush0**
My first contribution to micropython-lib.
SHA-X ported from PyPy
hmac ported from CPython 3.3
base64 ported from CPython 3.3
unhexlify is custom as PyPy's version was even slower.

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks for the contribution, much appreciated! However, there're few issues with the patches as provided. I'm currently travelling, so can't provide complete feedback at once, so going to add quick comment by comment, with the intention to give quick feedback rather than wait week(s).

So, issue no.1: general composition of patches (mostly commit messages) - it doesn't follow existing commits. I may imagine that it may be not immediately obvious which patterns are used, so I started this page to collect explicit requirements (WIP): https://github.com/micropython/micropython-lib/wiki/ContributorGuidelines

**Comment by pfalcon** [comment]
2. uPy already has (C) implementation of sha256: http://docs.micropython.org/en/latest/library/uhashlib.html

**Comment by pfalcon** [comment]
3) You mix patches for different modules in one pull request, which complicates review. (One PR for one module is good rule of thumb).

**Comment by pfalcon** [comment]
4) You appear to miss adding new files (or see 3) for things which complicate review).

**Comment by pfalcon** [comment]
5) having more hash algos is definitely good, but I'd like to hear your reasons for why it's useful ;-). The issue is that a specific application rarely needs to use more than 1. Then, you definitely have right direction of putting each algo in a separate module (sha512, sha224, etc.), but I don't see your taking special measures to benefit from that - hashlib module will import them all, and take a lot of memory.

**Comment by pfalcon** [comment]
6) Implementing stuff in Python is nice idea, which I myself advocate. But at least for some functionality (e.g. base64) it's clear that it's important to have it implemented in C as micropython extmod. Do you really want to have Python implementation which is to be dismissed by C implementation soon (or not so soon, depends on when somebody contributes it)?

**Comment by slush0** [comment]
ad 1 + 3 + 4) I reworked commits, please review now.

ad 2) I know there's sha256 in uhashlib, but sha224 need pure implementation of sha256 anyway, so I ported whole module and it's developer choice if he'll use uhashlib or full hashlib.

ad 5) I never worked with memory-restricted python before, so I did not realize this is a problem. shaX are completely separate modules now, so "from hashlib.sha256 import sha256" will work. Unfortunately it breaks CPython compatibility as "from hashlib import sha256" won't work.

ad 6) "Soon" (tm) :-) It is okay to replace pure-python implementation by native C in the future. For my project I need any implementation, and pure-python libraries are the way how I can contribute to Micropython project right now. Anyway, pure-python libraries are IMO more flexible for future development.

**Comment by pfalcon** [comment]
Thanks for the refactors, it looks much better now. But there're still not clear enough things ;-).

So, let's go module by module, starting with hmac.

Why did you change it to accept bytearrays in addition to bytes?

**Comment by pfalcon** [comment]
And can you please confirm the exact Python version you took it from. I used 3.3.3 as a source, so that's what I look at, and I for example don't see "name" property there.

Just to clarify: I very much appreciate your contribution, without people contributing the project won't progress much. But it's a peculiar project, where most code comes from upstream projects, and it must be done very carefully, or otherwise it will turn into unmaintainable mess. For example, consider that you took module from 3.3.1. Then someone wants to upgrade to 3.3.3, or to 3.4. It's one thing to port 5 changed lines, and another - half of the file. The first is relatively easy to do, if those 5 lines are very visible (uPy changes go in a separate commit), but changing half of lines here and there is big trouble. So, the idea is to apply porting effort and scrutiny on the micropython-lib input, once per module, to get as trouble-free maintenance as possible later. Otherwise, you can just assume that any your work will be overwritten later, because nobody will re-do work (number of upgrades) x (number of modules) times. So, that's it, these points are now added to https://github.com/micropython/micropython-lib/wiki/ContributorGuidelines also.

**Comment by pfalcon** [comment]
Ok, I figured it out: contrary to commit message saying "hmac: Ported from CPython 3.3", it was actually taken from 3.4.2. And I see that it's not the bets module to start from, as it depends on hashlib, but that was the only module which had its source specified in commit message.

**Comment by pfalcon** [comment]
> ad 5) I never worked with memory-restricted python before, so I did not realize this is a problem. shaX are completely separate modules now, so "from hashlib.sha256 import sha256" will work. Unfortunately it breaks CPython compatibility as "from hashlib import sha256" won't work.

You're right, sorry for sending you the wrong way :-(. Compatibility is apparently more important than efficiency here (for efficiency, we have uhashlib). But the problem comes up not the first time, I wonder if we need to implement descriptors in uPy to tackle it, after all.

**Comment by pfalcon** [comment]
Ok, I reworked haslib and hmac per ideas above (so changes to upstream were minimized and clearly visible), and pushed to master. Please have a look how it was done. I'll look at base64 stuff as time permits.

**Comment by pfalcon** [comment]
Ok, so "binascii: Added custom unhexlify implementation" contains not only unhexlify() implementation, but also base64 functions, then another implementation of base64 is coming with base64 module. I assume, implementation in binascii is superfluous?

**Comment by pfalcon** [comment]
Aha, right, base64 module implements only base32 itself, and imports the rest from binascii.

**Comment by slush0** [comment]
Dependency of base64 to binascii just copy the dependency model from CPython stdlib.

**Comment by pfalcon** [comment]
Cleaned up and pushed binascii module.

**Comment by slush0** [comment]
I just commited faster unhexlify. Can you pick this commit or should I do separate PR just for that? I think its my last commit to that area.

**Comment by slush0** [comment]
Anyway, instead of using "from sha256 import *" in hashlib/hashlib/__init__.py, this would be better:

```
from .sha256 import sha224, sha256
from .sha512 import sha384, sha512
```

if I'm not mistaken, this avoids importing of supporting memory structures and significantly reduces memory footprint of the library until such methods are invoked.

**Comment by pfalcon** [comment]
> I just commited faster unhexlify. Can you pick this commit or should I do separate PR just for that? I think its my last commit to that area.

Cherry-picked it. (Please use git pull --rebase to pull from master.)

**Comment by pfalcon** [comment]
Of these, base64 turned to be the hardest. Not only because I had to revert a lot of your removals, but be cause it really uncovers couple of non-implemented features in uPy. I thus don't feel comfortable to merge it master, instead pushed my cleanups to https://github.com/micropython/micropython-lib/tree/base64-cpy so far.

**Comment by pfalcon** [comment]
> Anyway, instead of using from sha256 import * in hashlib/hashlib/__init__.py, this would be better:

Fixed.

> this avoids importing of supporting memory structures and significantly reduces

A module is imported on its own completely in either case. What varies is how much of imported module's symbols get copied to current module's namespace.

**Comment by pfalcon** [comment]
> I thus don't feel comfortable to merge it master, instead pushed my cleanups to https://github.com/micropython/micropython-lib/tree/base64-cpy so far.

To clarifu, one thing about I wasn't comfortable is patching array slice assignments. Cases like this should be good motivation to implement such missing features. So, I implemented it in https://github.com/micropython/micropython/commit/cefcbb22b2befac1baa9953c477fcee4031635d3 , but we're really arrived at case of diminishing returns - remaining missing features are so infrequently used, that relatively significant code size increase they bring is hard to justify - at least for all ports. So, I enabled it for unix port of course, but chickened out to do that for stmhal, etc. So, @slush0, can you confirm whether you wanted this code to be run on unix or stmhal? In the latter case, your working around array slice assignment is probably makes sense.

**Comment by slush0** [comment]
Yes, I'm targeting to stmhal arch.

Anyway, is there any point in implementing some feature only for one architecture? I mean - code tested on unix should be running on stmhal without changes...

**Comment by pfalcon** [comment]
Not implementing for one architecture, but selectively enabled/disabled per port. @dpgeorge: Do you have opinion on enabling patch linked above for stmhal?

**Comment by dpgeorge** [comment]
I've wanted this feature for some time in stmhal but not got round to implementing it, so thanks!  Basically it allows you to "memmove/memcpy" which is very useful when trying to get away from any heap allocation.  I'll enable it in stmhal.

**Comment by pfalcon** [comment]
Thanks @dpgeorge for confirming that array slice assignment is useful. But I decided to leave @slush0's patches to avoid it in base64 module just in case it ever will be used on a port with slice assignment disabled.

So, all modules are merged now, thanks @slush0! But please make future pull requests module by module ;-). Btw, feel free to share how porting elliptic curve crypto goes - probably, on the forum.

**Pull request closed without merging**
