### PR TITLE
Fixed SyntaxError in subscribe()

### PR DESCRIPTION
**Pull request by Himura2la**
```python
>>> 1.to_bytes(1)
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax for number
```

### CODE REVIEW

**Comment by pfalcon** [comment]
So, what's exactly being fixed here?

**Comment by Himura2la** [comment]
I had an exception on this string, because `int()` has no `to_bytes()` method. I call `subscribe()` without QoS and it makes QoS become `1`.

**Comment by pfalcon** [comment]
> because int() has no to_bytes() method. 

Of course it has:

~~~
MicroPython v1.9.2-96-g3c7f2184b-dirty on 2017-09-19; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> (1).to_bytes(1, "little")
b'\x01'
~~~

**Comment by Himura2la** [comment]
I'll check it once again with the second argument, but the version cloned yesterday (with one argument) did not work for me, I posted the output from ESP8266 in the first comment

**Comment by Himura2la** [comment]
So do you see the issue now?

**Comment by pfalcon** [comment]
I don't, sorry. As far as I can tell, the issue you had was because you used a wrong branch of the project. That branch was rebased since, but why did you use it in the first place?

**Comment by Himura2la** [comment]
I don't see the correct syntax neither in **master** not in **mqtt** branch. If I don't pass a tuple to `qos`, it becomes int https://github.com/Himura2la/micropython-lib/blob/master/umqtt.simple/umqtt/simple.py#L144 and failing here https://github.com/Himura2la/micropython-lib/blob/master/umqtt.simple/umqtt/simple.py#L152

Just tested on my ESP8266, ints have no `.to_bytes()`

```python
MicroPython v1.9.1-8-g7213e78d on 2017-06-12; ESP module with ESP8266
Type "help()" for more information.
>>> 1.to_bytes(1, "little")
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax for number
>>>
```

**Comment by Himura2la** [comment]
I don't see the correct syntax neither in **master** not in **mqtt** branch. If I don't pass a tuple to `qos`, it becomes int https://github.com/micropython/micropython-lib/blob/master/umqtt.simple/umqtt/simple.py#L144 and failing here https://github.com/micropython/micropython-lib/blob/master/umqtt.simple/umqtt/simple.py#L152

Just tested on my ESP8266, ints have no `.to_bytes()`

```python
MicroPython v1.9.1-8-g7213e78d on 2017-06-12; ESP module with ESP8266
Type "help()" for more information.
>>> 1.to_bytes(1, "little")
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax for number
>>>
```

**Comment by dpgeorge** [comment]
@Himura2la the problem was simply that `1.to_bytes(...)` looks like a decimal number to Python and so that's why it gives a syntax error.  It can be fixed by putting a space before the period: `1 .to_bytes(...)`, or as shown above putting the number in parenthesis: `(1).to_bytes(...`).  Note that it's not a tuple with one element, that would be `(1,).to_bytes(...)` which doesn't work (tuple doesn't have a to_bytes method).  And since `qos` is not an integer literal that works fine without a space.  This is all standard Python behaviour.

**Comment by Himura2la** [comment]
Thanks for explanation, there are some quite confusing dark corners of Python...

**Pull request closed without merging**
