### PR TITLE
random: A version of Random hacked-down from Cpython

### PR DESCRIPTION
**Pull request by pramasoul**
Uses 128-bit xorshift generator, with fallback to linear congruential, instead of the massive Mersenne Twister of Cpython implementation.

Where does this work belong? Does this belong in micropython-lib? How should it be improved?

### CODE REVIEW

**Comment by pfalcon** [comment]
> Where does this work belong? Does this belong in micropython-lib?

Well, my idea has always been to provide small, but adequate, PRNG via C codebase (perhaps urandom module), consistent for all ports. And my idea was to develop full-fledged random module from scratch, to make sure it's minimal and well suited to be used on bare-metal ports. I didn't make any progress on that because surprisingly, I didn't face a need for random module yet.

So, seeing this code drop with 700+ lines of CPython code, I can't say I'm too excited. Of course, if there's argumentation "CPython's doesn't really contain much unneeded stuff" (I didn't look closely myself), then maybe, but then it still should follow https://github.com/micropython/micropython-lib/wiki/ContributorGuidelines : 

> Start with committing 3rd-party source as-is, clearly stating in commit message from where it was taken (exact version, preferrably with URL to tarball, or VCS revision, preferrably with URL to it).

> Follow up with your changes as a next commit.

**Comment by dpgeorge** [comment]
The code here is rather large.  Probably 50% is comments and/or doc strings, which are arguably not needed.

**Comment by pramasoul** [comment]
This is helpful. I hit a need for repeatable PRNG for testing on the pyboard, and one thing led to another.

Cpython ```Random``` is well-tested, and is a standard interface. But it's got methods that that are just bloat, until the day you really need ```vonmisesvariate()```. Such methods should only be present in RAM when needed, perhaps by being late-loaded and dynamically-bound. Can I import a function and dynamically bind it to a class in micropython? Micropython ```cannot create 'bound_method' instances``` so this Cpython idiom doesn't work:
```python
from types import MethodType

class Foo():

    def fun(self, *args, **kwargs):
        from somewhere import fun
        self.fun = MethodType(fun, self)
        return self.fun(*args, **kwargs)
```
Would a ```bound_meth_make_new()``` be possible? Or is there a better way to keep the API but run lean?

**Comment by pfalcon** [comment]
> so this Cpython idiom doesn't work:

Feel free to report this as a bug to micropython, so it wasn't forgotten. Preferrably, with references, because I for example first time see such code.

> Or is there a better way to keep the API but run lean?

Yes, I think starting with the minimal implementation, and then extending it only on the real need, carefully logging what needed more stuff, and why, is a better approach.

**Comment by pfalcon** [comment]
MicroPython now has urandom.getrandbits() builtin function, from which other functions can be implemented. But it would be nice to do this functions by function, as actually needed, to make "random" module work on MCU systems.

**Comment by jimmo** [comment]
We now have `getrandbits` (and `seed` which solves the repeatable part), and subsequently a micropython-lib random.py has been added which adds additional functions (e.g. random.shuffle). This would be a good base to start adding more functions from Python (e.g. random.choice for boards that don't include it).

**Pull request closed without merging**
