### PR TITLE
Simplification of delay during reconnect

### PR DESCRIPTION
**Pull request by kfricke**
The delay method was wasting an argument, static class member and only got called from one location.

### CODE REVIEW

**Comment by pfalcon** [comment]
umqtt.robust.MQTTClient is intended to be configurable, extensible, and subclassable by a user.

**Comment by kfricke** [comment]
But a base class should at least show reasonable behaviour and wasteless implementation.

**Comment by pfalcon** [comment]
And that's exactly what it does.

**Comment by kfricke** [comment]
The argument i passed to the method delay is never used. I did assume that your intent was to pass a dynamic delay, which does increase over time when the connection keeps failing.
Dropping the method was just another brave brevity.

**Pull request closed without merging**
